services:
  - type: worker
    name: canvas-discord-announcer
    runtime: node
    plan: free
    buildCommand: "npm install"
    startCommand: "npm start"
    autoDeploy: true
    envVars:
      - key: POLL_INTERVAL
        value: "600"
      - key: CANVAS_BASE
        sync: false
      - key: CANVAS_TOKEN
        sync: false
      - key: CANVAS_COURSE_ID
        sync: false
      - key: DISCORD_TOKEN
        sync: false
      - key: DISCORD_CHANNEL_ID
        sync: false
